language: go

go:
  #- 1.0
  #- 1.1
  #- 1.2
  #- 1.3
  #- 1.4
  #- 1.5
  #- 1.6
  #- 1.7
  - '1.8'
  - '1.9'
  - '1.10'
  - '1.11'
  - tip

services:
  - mysql

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
